// Written by Cornell Washington; boilerplate generated by https://ideone.com

import java.util.*;
import java.lang.*;
import java.io.*;

class Week1
{
	public static void main (String[] args) throws java.lang.Exception
	{
		double salary = 0.0;
		String name = "";
		Scanner scanner = new Scanner(System.in);

		System.out.print("Hello, what is your name? ");
		name = scanner.nextLine(); // allow user to enter full name

		System.out.print("Nice to meet you, what is your weekly salary? ");
		salary = scanner.nextDouble();

		// formatted string
		System.out.printf("Thank you %s, we will increase your weekly salary by $50. Your new weekly salary is $%.2f.", name, salary+50.0);
	}
}
